spring:
  application:
    name: "cloud-native-buildpack-sample"

# Customize Spring Boot Info actuator
info:
  java.vm.vendor: ${java.vm.vendor}
  java.version: ${java.version}
  application.encoding: @project.build.sourceEncoding@
  application.name: ${spring.application.name}
  spring.boot.version: @spring-boot.version@

# Expose all Spring Boot Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*"